#!/bin/bash
#SBATCH --job-name=gprmax_test
#SBATCH --output=logs/test_single.out
#SBATCH --error=logs/test_single.err
#SBATCH --partition=cpu
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8

# Single-job smoke test: runs scenario_001_tx01 only.
# Input file is taken from brain_inputs/ (generated by generate_dataset.py).
# Do NOT edit the .in file by hand — regenerate with: python generate_dataset.py
#
# Usage (from project root on HPC):
#   mkdir -p logs
#   sbatch test_single/run_simulation.sh

echo "========================================"
echo "gprMax Single-Job Smoke Test"
echo "Node: $SLURM_NODELIST"
echo "Start time: $(date)"
echo "========================================"

# Activate conda environment
source "$HOME/miniconda3/etc/profile.d/conda.sh"
conda activate gprmax
PYTHON="$HOME/miniconda3/envs/gprmax/bin/python"

INPUT_FILE="brain_inputs/scenario_001_tx01.in"

if [ ! -f "$INPUT_FILE" ]; then
    echo "ERROR: $INPUT_FILE not found. Run: python generate_dataset.py"
    exit 1
fi

echo "Input: $INPUT_FILE"
echo ""

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
$PYTHON -m gprMax "$INPUT_FILE" -n 1

OUTPUT_FILE="${INPUT_FILE%.in}.out"
if [ -f "$OUTPUT_FILE" ]; then
    echo ""
    echo "✓ Simulation completed: $OUTPUT_FILE ($(du -h $OUTPUT_FILE | cut -f1))"
    # Quick sanity check: confirm tls group with 16 transmission lines exists
    $PYTHON -c "
import h5py, sys
f = h5py.File('$OUTPUT_FILE', 'r')
tls = list(f.get('tls', {}).keys())
print(f'  TL channels found: {len(tls)} -> {tls}')
if len(tls) != 16:
    print('  WARNING: expected 16 TL channels')
    sys.exit(1)
print('  OK: all 16 TL channels present')
"
else
    echo "✗ ERROR: output file not created"
    exit 1
fi

echo ""
echo "End time: $(date)"
echo "========================================"
echo ""
echo "End time: $(date)"
echo "========================================"
